name : ECS Deployment
on : 
   push : 
      branches : 
         - main 
      workflow_dispatch :

env:
   NODE_IMAGE_NAME : ecs-demo-node

jobs : 
    build-image-push : 
      runs-on : ubuntu-latest
      steps:
          - name: Check out the repo
            uses: actions/checkout@v3

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Add Details to image
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ vars.DOCKER_USERNAME }}/${{ env.NODE_IMAGE_NAME }}
              tags: |
                latest
                v1.0.${{github.run.number}}

          - name: Build and push Docker image
            id: push
            uses: docker/build-push-action@v6
            with:
              context: ./API-jokes
              file: ./API-jokes/Dockerfile.prod
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}